# Generated by Django 4.1.2 on 2022-10-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Specialtopic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='User',
        ),
    ]
