# Generated by Django 4.1.1 on 2022-09-15 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Specialtopic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_database',
            name='Date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
