# Generated by Django 4.1.2 on 2022-10-19 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Specialtopic", "0002_rename_contact_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student_database",
            fields=[
                ("Student_name", models.CharField(max_length=50)),
                (
                    "USN",
                    models.CharField(max_length=11, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="System_database",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField(auto_now_add=True)),
                ("Student_name", models.CharField(max_length=50)),
                (
                    "Branch",
                    models.CharField(
                        choices=[
                            ("cs", "CSE"),
                            ("ec", "ECE"),
                            ("as", "ASE"),
                            ("me", "Mech"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "System_no",
                    models.CharField(
                        choices=[
                            ("s1", "System1"),
                            ("s2", "System2"),
                            ("s3", "System3"),
                            ("s4", "System4"),
                            ("k1", "Kindle1"),
                            ("k2", "Kindle2"),
                        ],
                        max_length=9,
                    ),
                ),
                ("Time_in", models.TimeField()),
                ("Time_out", models.TimeField()),
                (
                    "USN",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Specialtopic.student_database",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="User",),
    ]
