# Generated by Django 4.1.1 on 2022-10-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Specialtopic', '0003_remove_student_database_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_database',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_database',
            name='USN',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='system_database',
            name='Branch',
            field=models.CharField(choices=[('cs', 'CSE'), ('ec', 'ECE'), ('as', 'ASE'), ('me', 'Mech')], max_length=10),
        ),
        migrations.AlterField(
            model_name='system_database',
            name='System_no',
            field=models.CharField(choices=[('s1', 'System1'), ('s2', 'System2'), ('s3', 'System3'), ('s4', 'System4'), ('k1', 'Kindle1'), ('k2', 'Kindle2')], max_length=9),
        ),
        migrations.AlterField(
            model_name='system_database',
            name='USN',
            field=models.CharField(max_length=11),
        ),
    ]
