# Generated by Django 4.1.1 on 2022-10-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Specialtopic', '0005_remove_student_database_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_database',
            name='System_no',
        ),
    ]
