# Generated by Django 4.1.1 on 2022-10-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Specialtopic", "0002_system_database_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="system_database",
            name="Date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
