# Generated by Django 4.1.1 on 2022-10-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Specialtopic', '0006_remove_system_database_system_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_database',
            name='System_no',
            field=models.CharField(choices=[('s1', 'System1'), ('s2', 'System2'), ('s3', 'System3'), ('s4', 'System4'), ('k1', 'Kindle1'), ('k2', 'Kindle2')], default=1, max_length=9),
            preserve_default=False,
        ),
    ]
